### ISSUE TITLE
Second factor email not received, can't log in

### ISSUE THREAD

**Issue by jvasile** [PermanentOrg/web-app#191]
I cannot complete the log in flow to access my permanent account.

Yesterday I tried to log in to my account (user email is jvasile AT gmail).  I was prompted for a second factor code, but never received one in my inbox  containing the code.  I checked spam too.  I tried this process twice, with the same result each time.  I just checked again now and see no email in my inbox, so it is not likely to just be a delay in delivery.

I have received such emails in the past with the subject line "Verify your identity at Permanent.org".

I note as well that there is no "resend email" button on the page that asks me for a code.  This is a minor inconvenience.

Let me know if I can help debug in any way.

Thank you!

**Comment by cecilia-donnelly** [comment]
James! First off, I or any admin can remove your MFA so you can at least log in, if you'd like.

I do see an [issue in Sentry](https://permanentorg.sentry.io/issues/3409212100/events/4bb06c6709524010a2947f16f482ec0a/?project=3663562), but my memory is that that error is a bit misleading.

Paging @k8lyn6 who has a lot of experience with this category of errors.

**Comment by k8lyn6** [comment]
Hi @jvasile ! I looked in our Mandrill email outbox, and I do see two authentication emails sent to your email address yesterday. Can you double check again that they didn't land in your spam? If they aren't there, @cecilia-donnelly I'm not sure what the next steps are to troubleshoot.

**Comment by cecilia-donnelly** [comment]
Thanks for looking @k8lyn6! I believe we changed auth providers since the last time you logged in, @jvasile, so maybe the emails are now being caught by some filter they were escaping before?

**Comment by jvasile** [comment]
Ah, I found it.  It was in spam.  And I didn't see it because the new provider has a different subject line: "Your Multi-Factor Authentication code for Permanent.org"  I marked it ham.

I guess we can close this.  Thanks all!

**Comment by cecilia-donnelly** [comment]
Great!
