### ISSUE TITLE
478 vulnerabilities

### ISSUE THREAD

**Issue by xmunoz** [PermanentOrg/web-app#56]
#### Current Behavior
```
found 478 vulnerabilities (2 low, 146 moderate, 328 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

#### Steps to Reproduce
```
npm install
```

#### Expected Behavior
Packages are automagically kept up to date.

#### Possible Solutions
Configure dependabot

**Comment by dyerjos** [comment]
[audit_16APR2022.txt](https://github.com/PermanentOrg/web-app/files/8502219/audit_16APR2022.txt)

I agree that a lot of these security problems are related to this web-app using Angular v10 which is no longer supported by Google. In fact even v11 of Angular loses support May 11th so I recommend this project gets bumped up to V13. 

Angular[ release schedule](https://angular.io/guide/releases)

[This link](https://update.angular.io/?v=10.1-11.0) will provide instructions on how to update Angular version by version but there are other libraries that will need updated as well such as @angular/fire.

**Comment by dyerjos** [comment]
While on the top on updating dependencies, I recommend bumping Node.js from V14 to V16. While trying to get the app setup locally to run some tests I encountered an error possibly related to V14 [here](https://github.com/angular/angular-cli/issues/19644).

Node.js [release schedule](https://nodejs.org/en/about/releases/)

**Comment by meisekimiu** [comment]
We upgraded Angular. While there are still vulnerable dependencies, these should be handled by dependabot and a separate issue will be created to handle a specific set of vulnerable dependencies.
