### ISSUE TITLE
Update the error message to match the backend value.

### ISSUE THREAD

**Issue by mithuna** [PermanentOrg/web-app#61]
The back-ends has updates the message when user try to share with themself in[ this PR](https://bitbucket.org/permanent-org/back-end/pull-requests/109/user-shouldnt-be-allowed-to-share-to-self)
Update [this ](https://github.com/PermanentOrg/web-app/blob/b88f720c315971297016096fbb5673861925fb85/constants/master_en.json#L1160) message

**Comment by meisekimiu** [comment]
Closed by #62
