### ISSUE TITLE
Need Linting / Formatting Tool

### ISSUE THREAD

**Issue by meisekimiu** [PermanentOrg/web-app#91]
While we're eventually going to work on adding `eslint` to the web-app, I want to put a ticket here in the repo because certain spacing styles are inconsistent with the app and my IDE is freaking out over how exactly to indent things (Specifically within the `AuthModule` for whatever reason). I would like to run some kind of formatter to end these troubles and so I don't have to worry about how many spaces I need to indent everything by, knowing that the formatter can fix everything later.

**Comment by dyerjos** [comment]
I recommend using eslint with [prettier](https://prettier.io/). Something like [this](https://gist.github.com/Imshyamal/95833b32124c68480737f2a28f0a37d4)
